import Head from "next/head";
import Show from "../Components/Show";
import AutoSlider from "../Components/AutoSlider";
import { motion } from "framer-motion";
import Texter from "../Components/Texter";

export default function Home() {
  return (
    <div className="select-none cursor-default overflow-x-hidden">
      <Head>
        <title>Active inShop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="content mt-2 flex justify-center overflow-hidden">
        <motion.main
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1 }}
          className="flex flex-wrap gap-2 w-screen justify-center"
        >
          <Show />
          <div className="">
            <Texter />
          </div>
          <div className="">
            <AutoSlider />
          </div>
        </motion.main>
      </div>
    </div>
  );
}
