import ProductContext from "../Context/productContext";
import { useContext } from "react";
import Featured from "../Components/Featured";
import ProductWidget from "../Components/ProductWidget";
import { motion } from "framer-motion";
import Head from "next/head";

export default function Wishlist() {
  const { wishList, addToWish, removeFromWish, currency, getOne, featured } =
    useContext(ProductContext);
  if (wishList.length === 0) {
    return (
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1 }}
        className="flex flex-col items-center justify-center px-4 text-4xl"
      >
        <Head>
          <title>WishList</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex flex-1 flex-col items-center">
          The list is empty
        </div>
        <div className="mt-40 flex-1 flex-col flex gap-2 text-lg">
          <p className="text-lg text-neutral-700">
            But here is something that you can add to your list.
          </p>
          <div className="flex gap-2 flex-wrap justify-center">
            {featured.map((product) => (
              <ProductWidget
                product={product}
                getOne={getOne}
                key={product.id}
                addToWish={addToWish}
              />
            ))}
          </div>
        </div>
      </motion.div>
    );
  } else {
    return (
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1 }}
        className="flex flex-col gap-4 mt-4 px-10"
      >
        <Head>
          <title>WishList</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className="text-4xl text-neutral-500">WishList</h1>
        <div className="flex gap-4 items-center flex-wrap justify-center">
          {!wishList ? (
            <div>Loading...</div>
          ) : (
            wishList.map((product, i) => (
              <div className="relative" key={i}>
                <div
                  onClick={(e) => {
                    removeFromWish(product);
                  }}
                  className="remove absolute bottom-0 z-20 h-10 w-full justify-center bg-red-600 flex items-center cursor-pointer hover:border-2 border-neutral-500 movement"
                >
                  Remove
                </div>
                <ProductWidget
                  product={product}
                  currency={currency}
                  getOne={getOne}
                  wishList={wishList}
                />
              </div>
            ))
          )}
        </div>
      </motion.div>
    );
  }
}
